# Site settings
author: Peter Bedrosian
title: Coding, who knew. 
header-img: img/home-bg.png
email: peter_bedrosian@yahoo.com
copyright_name: Peter Bedrosian
description: > # this means to ignore newlines until "baseurl:"
  The Journey Begins 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pbedrosian

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
